#!/bin/bash

export FOUNDATIONS_HOME=${FOUNDATIONS_HOME:-~/.foundations}

export ATLAS_PORT=${ATLAS_PORT:-37722}
export ORBIT_PORT=${ORBIT_PORT:-37222}

export SCHEDULER_PORT=${SCHEDULER_PORT:-5000}
export SCHEDULER_HOST=${SCHEDULER_HOST:-localhost}
export FOUNDATIONS_SCHEDULER_URL=http://${SCHEDULER_HOST}:${SCHEDULER_PORT}

export REDIS_HOST=${REDIS_HOST:-localhost}
export REDIS_PORT=${REDIS_PORT:-6379}
export REDIS_URL="redis://$REDIS_HOST:$REDIS_PORT"

export F9S_LOG_DIR=$FOUNDATIONS_HOME/logs
mkdir -p $F9S_LOG_DIR

export ARCHIVE_DIR=$FOUNDATIONS_HOME/job_data
mkdir -p $ARCHIVE_DIR

export WORKING_DIR=$FOUNDATIONS_HOME/local_docker_scheduler/work_dir
mkdir -p $WORKING_DIR

export JOB_BUNDLE_STORE_DIR=$FOUNDATIONS_HOME/job_bundle_store_dir
mkdir -p $JOB_BUNDLE_STORE_DIR

export NUM_WORKERS=0
export LOCAL_DOCKER_SCHEDULER_DIR=../local-docker-scheduler

export LOCAL_DOCKER_SCHEDULER_HOST=${LOCAL_DOCKER_SCHEDULER_HOST:-localhost}
export REMOTE_FOUNDATIONS_HOME=${REMOTE_FOUNDATIONS_HOME:-$FOUNDATIONS_HOME}