#!/usr/bin/python

input_base_path = "/opt/ml/input/data/training"

def get_job_name():
    from glob import glob
    from os.path import basename

    archive_paths = glob(input_base_path + "/*.tgz")
    return basename(archive_paths[0])[:-4]

def load_job(job_name):
    import tarfile
    with tarfile.open(input_base_path + "/" + job_name + ".tgz") as tar:
        tar.extractall(job_name)

def main():
    from os import chdir
    from glob import glob
    from subprocess import call
    from sys import exit

    job_name = get_job_name()
    load_job(job_name)
    chdir(job_name)
    call(["chmod", "a+x", "run.sh"])
    ret_code = call(["./run.sh"])
    exit(ret_code)

if __name__ == "__main__":
    main()