"""
Copyright (C) DeepLearning Financial Technologies Inc. - All Rights Reserved
Unauthorized copying, distribution, reproduction, publication, use of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Thomas Rogers <t.rogers@dessa.com>, 06 2018
"""

from foundations.hyperparameter import Hyperparameter
from foundations.job import Job
from foundations.result_reader import ResultReader
from foundations_internal.pipeline_archiver import PipelineArchiver
from foundations.context_aware import context_aware
from foundations.pipeline_archiver_fetch import PipelineArchiverFetch
from foundations.global_state import *
from foundations.deployment_utils import *
from foundations.job_persister import JobPersister
from foundations_contrib.null_archive import NullArchive
from foundations_contrib.null_pipeline_archive_listing import NullArchiveListing
from foundations_contrib.local_file_system_pipeline_archive import LocalFileSystemPipelineArchive
from foundations_contrib.local_file_system_bucket import LocalFileSystemBucket
from foundations_contrib.simple_worker import SimpleWorker
from foundations_contrib.simple_bucket_worker import SimpleBucketWorker
from foundations_internal.compat import compat_raise
from foundations_contrib.local_file_system_pipeline_listing import LocalFileSystemPipelineListing
from foundations_contrib.local_shell_job_deployment import LocalShellJobDeployment
from foundations_contrib.local_file_system_cache_backend import LocalFileSystemCacheBackend
from foundations_contrib.bucket_pipeline_archive import BucketPipelineArchive
from foundations_contrib.bucket_pipeline_listing import BucketPipelineListing
from foundations_contrib.prefixed_bucket import PrefixedBucket
from foundations_internal.serializer import *
from foundations.discrete_hyperparameter import DiscreteHyperparameter
from foundations.integer_hyperparameter import IntegerHyperparameter
from foundations.floating_hyperparameter import FloatingHyperparameter
from foundations_contrib.middleware.basic_stage_middleware import BasicStageMiddleware
from foundations_contrib.change_directory import ChangeDirectory
from foundations_contrib.bucket_job_deployment import BucketJobDeployment
from foundations.deployment_wrapper import DeploymentWrapper
from foundations.stage_logging import log_metric
from foundations.staging import create_stage
from foundations.projects import set_project_name, get_metrics_for_all_jobs
from foundations_internal.scheduler import Scheduler
from foundations_internal.versioning import __version__
import foundations_internal.import_installer
import foundations_contrib.consumers


def _append_module():
    import sys
    module_manager.append_module(sys.modules[__name__])


_append_module()
